name: lyrica
description: A Flutter application for music playback and management.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  just_audio: ^0.9.0
  flutter_downloader: ^1.7.0
  device_info_plus: ^3.0.0
  permission_handler: ^10.0.0
  cloud_firestore: ^3.1.0
  google_fonts: ^2.1.0
  font_awesome_flutter: ^10.0.0
  external_path: ^2.0.0
  flutter_screenutil: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/rewardIcon.png
    - assets/image/music_note.png
    - assets/image/other_assets/